[project]
name = "cs336-lecture-notes"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "torch>=2.9.0",
]

[[tool.uv.index]]
url = "https://pypi.org/simple"
default = true
